### ISSUE TITLE
Is this SDK maintained? 

### ISSUE THREAD

**Issue by isik-kaplan** [iyzico/iyzipay-python#67]
Looks like for the last 3-4 years there haven't been much of a code change, addition or revision at all. Is this SDK maintainer or are we supposed to fork this and move away from the official SDK? 

Issues don't seem to be fixed, code seems heavily bugged, documentation is not really up to date nor enough, PRs are not reviewed nor merged. 

If this is no longer under maintenance, please do let me know so that I can just move on to my own fork. 

Thanks!

**Comment by ShopskaSalad** [comment]
Hey @isik-kaplan
Above all, we are very grateful for your detailed comments, notices and your contribution on iyzico open source platform.
I would like to begin with answering your questions and asking a question at the end.
`Is this SDK maintained?
`
Yes the https://github.com/iyzico/iyzipay-python is maintaining, yet as iyzico is a rapidly growing platform so there will be always some issues and we will be always resolving 🛠️ 

`let me know so that I can just move on to my own fork.`
That is something we truly admire, please write us on here or from destek@iyzico.com in case of support needed 🚀 

And finally, could you please share with us that which product do you trying to use but can't? 
So I can directly help you to resolve your issue.
Waiting to hearing from you.
Happy merry coding! 🎅 ✌️

**Comment by isik-kaplan** [comment]
Hey, thanks for the response.

As a freelancer I keep re-writing the same code for integrations in case the clients want the same integration, in your case payment gateway integration. This was the very first time I've used iyzico and I'm glad you have an SDK. But even with the SDK, and I hope you don't get this the wrong way, iyzico is really hard to integrate unlike its counterparts, stripe/braintree/paypal etc. 

I think the issue is not only the python SDK but the underlying api's lack of documentation, and responses. During the integration I've kept getting some error codes from the api that documentation lacked the necessary information or fix for. I can grab some tangible examples from my previous integration for your to look at in case you are interested. 

If you people are working on the documentation, or are willing to work on the documentation, I might even give you a boost on the python side with maybe even re-implementing your entire sdk for you. Hey, this is what open source is all about, right? 

Given that you guys provide roughly the same service for cheaper than your counterparts, I actually would suggest you guys to my clients and freelancer people around me in case you can make your api and documentation more developer friendly. 

Do let me know if and when the documentation improves, and I'll try my best to help you improve the SDKs I'm using.

**Comment by ShopskaSalad** [comment]
Hey @isik-kaplan,

First is first, thanks for all of your kind words and thoughts. 
It is really great to hear from our supporters. 💪 

As there are no issues to resolve I am currently closing this issue.
Yet,`my previous integration for your to look at in case you are interested.` please let us know those parts that you struggled on the new issues so we can examine or explain.

Thank you one more time to all contributions of open source at the Turkish server!
Cheers 🎉
